config/routes.rb
ActiveAnalytics::Engine.routes.draw do
  get "/assets/*file", to: "assets#show", constraints: {file: /.+/}, as: :asset

  get "/:site", to: "sites#show", as: :site, constraints: {site: /[^\/]+/}

  # Referrers
  get "/:site/referrers", to: "referrers#index", constraints: {site: /[^\/]+/}, as: :referrers
  get "/:site/referrers/*referrer", to: "referrers#show", as: :referrer, constraints: {site: /[^\/]+/, referrer: /.+/}

  # Browsers
  get "/:site/browsers", to: "browsers#index", constraints: {site: /[^\/]+/}, as: :browsers
  get "/:site/browsers/:id", to: "browsers#show", constraints: {site: /[^\/]+/}, as: :browser

  # Pages
  get "/:site/pages", to: "pages#index", constraints: {site: /[^\/]+/}, as: :pages
  get "/:site/*page", to: "pages#show", as: :page, constraints: {site: /[^\/]+/}

  root to: "sites#index", as: :active_analytics
end

app/models/active_analytics/application_record.rb
module ActiveAnalytics
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/active_analytics/browsers_per_day.rb
module ActiveAnalytics
  class BrowsersPerDay < ApplicationRecord
    # TODO: Deduplicate
    scope :top, -> (n = 10) { order_by_totals.limit(n) }
    scope :order_by_date, -> { order(:date) }
    scope :order_by_totals, -> { order(Arel.sql("SUM(total) DESC")) }
    scope :between_dates, -> (from, to) { where(date: from..to) }

    def self.append(params)
      total = params.delete(:total) || 1
      params[:site] = params[:site].downcase if params[:site]
      where(params).first.try(:increment!, :total, total) || create!(params.merge(total: total))
    end

    def self.group_by_name
      group(:name).select("name, sum(total) AS total")
    end

    def self.group_by_version
      group(:name, :version).select("version, sum(total) AS total")
    end

    def self.group_by_date
      group(:date).select("date, sum(total) as total")
    end

    def self.filter_by(params)
      scope = all
      scope = scope.between_dates(params[:from], params[:to]) if params[:from].present? && params[:to].present?
      scope = scope.where(site: params[:site]) if params[:site].present?
      scope = scope.where(name: params[:id]) if params[:id].present?
      scope = scope.where(version: params[:version]) if params[:version].present?
      scope
    end

    def to_param
      name
    end
  end
end

app/models/active_analytics/views_per_day.rb
module ActiveAnalytics
  class ViewsPerDay < ApplicationRecord
    validates_presence_of :site, :page, :date

    scope :between_dates, -> (from, to) { where("date BETWEEN ? AND ?", from, to) }
    scope :after, -> (date) { where("date > ?", date) }
    scope :order_by_totals, -> { order(Arel.sql("SUM(total) DESC")) }
    scope :order_by_date, -> { order(:date) }
    scope :top, -> (n = 10) { order_by_totals.limit(n) }

    class Site
      attr_reader :host, :total
      def initialize(host, total)
        @host, @total = host, total
      end
    end

    class Page
      attr_reader :host, :path, :total
      def initialize(host, path, total)
        @host, @path, @total = host, path, total
      end

      def url
        host + path
      end
    end

    def self.group_by_site
      group(:site).pluck("site, SUM(total)").map do |row|
        Site.new(row[0], row[1])
      end
    end

    def self.group_by_page
      group(:site, :page).pluck("site, page, SUM(total)").map do |row|
        Page.new(row[0], row[1], row[2])
      end
    end

    def self.group_by_referrer_site
      group(:referrer_host).pluck("referrer_host, SUM(total)").map do |row|
        Site.new(row[0], row[1])
      end
    end

    def self.group_by_referrer_page
      group(:referrer_host, :referrer_path).pluck("referrer_host, referrer_path, SUM(total)").map do |row|
        Page.new(row[0], row[1], row[2])
      end
    end

    def self.group_by_date
      group(:date).select("date, sum(total) AS total")
    end

    def self.to_histogram
      Histogram.new(self)
    end

    def self.append(params)
      total = params.delete(:total) || 1
      params[:site] = params[:site].downcase if params[:site]
      params[:referrer_path] = nil if params[:referrer_path].blank?
      params[:referrer_path] = params[:referrer_path].downcase if params[:referrer_path]
      params[:referrer_host] = params[:referrer_host].downcase if params[:referrer_host]
      where(params).first.try(:increment!, :total, total) || create!(params.merge(total: total))
    end

    SLASH = "/"

    def self.split_referrer(referrer)
      return [nil, nil] if referrer.blank?
      if (uri = URI(referrer)).host.present?
        [uri.host, uri.path.presence]
      else
        strings = referrer.split(SLASH, 2)
        [strings[0], strings[1] ? SLASH + strings[1] : nil]
      end
    end
  end
end

app/controllers/active_analytics/application_controller.rb
module ActiveAnalytics
  class ApplicationController < ActiveAnalytics.base_controller_class.constantize
    layout "active_analytics/application"

    helper PagesHelper
    helper SitesHelper
    helper BrowsersHelper

    private

    def from_date
      @from_date ||= Date.parse(params[:from])
    end

    def to_date
      @to_date ||= Date.parse(params[:to])
    end

    def require_date_range
      redirect_to(params.to_unsafe_hash.merge(from: to_date, to: from_date)) if from_date > to_date
    rescue TypeError, ArgumentError # Raised by Date.parse when invalid format
      redirect_to(params.to_unsafe_hash.merge(from: 7.days.ago.to_date, to: Date.today))
    end

    def current_views_per_days
      ViewsPerDay.where(site: params[:site]).between_dates(from_date, to_date)
    end

    def previous_views_per_days
      ViewsPerDay.where(site: params[:site]).between_dates(previous_from_date, previous_to_date)
    end

    def previous_from_date
      from_date - (to_date - from_date)
    end

    def previous_to_date
      to_date - (to_date - from_date)
    end
  end
end

app/controllers/active_analytics/assets_controller.rb
# frozen_string_literal: true

require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class AssetsController < ApplicationController
    protect_from_forgery except: :show

    @@root = ActiveAnalytics::Engine.root.join("app/views", controller_path + "/").to_s

    def self.endpoints
      return @endpoints if @endpoints
      paths = Dir["#{@@root}**/*"].keep_if { |path| File.file?(path) }
      files = paths.map { |path| path.to_s.delete_prefix(@@root).delete_suffix(".erb") }
      @endpoints = files.delete_if { |str| str.start_with?("_") }
    end

    def show
      if self.class.endpoints.include?(params[:file])
        expires_in(1.day, public: true)
        render_asset(params[:file])
      else
        raise ActionController::RoutingError.new("Not found #{params[:file]}")
      end
    end

    private

    def render_asset(path)
      ext = File.extname(params[:file])
      path_without_ext = path.delete_suffix(ext)
      mime_type = Mime::Type.lookup_by_extension(ext.delete_prefix("."))
      render("#{controller_path}/#{path_without_ext}", mime_type: mime_type)
    end
  end
end

app/controllers/active_analytics/browsers_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class BrowsersController < ApplicationController
    def index
      @histogram = Histogram.new(current_browsers_per_days.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_browsers_per_days.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @browsers = current_browsers_per_days.group_by_name.top(100)
    end

    def show
      @histogram = Histogram.new(current_browsers_per_days.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_browsers_per_days.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @browsers = current_browsers_per_days.group_by_version.top(100)
    end

    private

    def current_browsers_per_days
      BrowsersPerDay.filter_by(params)
    end

    def previous_browsers_per_days
      BrowsersPerDay.filter_by(params.merge(from: previous_from_date, to: previous_to_date))
    end
  end
end

app/controllers/active_analytics/pages_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class PagesController < ApplicationController
    include PagesHelper

    before_action :require_date_range

    def index
      @histogram = Histogram.new(current_views_per_days.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_views_per_days.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @pages = current_views_per_days.top(100).group_by_page
    end

    def show
      page_scope = current_views_per_days.where(page: page_from_params)
      previous_page_scope = previous_views_per_days.where(page: page_from_params)
      @histogram = Histogram.new(page_scope.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_page_scope.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @next_pages = current_views_per_days.where(referrer_host: params[:site], referrer_path: page_from_params).top(100).group_by_page
      @previous_pages = page_scope.top(100).group_by_referrer_page
    end
  end
end

app/controllers/active_analytics/referrers_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class ReferrersController < ApplicationController
    before_action :require_date_range

    def index
      @referrers = current_views_per_days.top(100).group_by_referrer_site
      @histogram = Histogram.new(current_views_per_days.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_views_per_days.order_by_date.group_by_date, previous_from_date, previous_to_date)
    end

    def show
      referrer_host, referrer_path = params[:referrer].split("/", 2)
      scope = current_views_per_days.where(referrer_host: referrer_host)
      scope = scope.where(referrer_path: "/" + referrer_path) if referrer_path.present?
      previous_scope = previous_views_per_days.where(referrer_host: params[:referrer])
      @histogram = Histogram.new(scope.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_scope.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @previous_pages = scope.top(100).group_by_referrer_page
      @next_pages = scope.top(100).group_by_page
    end
  end
end

app/controllers/active_analytics/sites_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class SitesController < ApplicationController
    before_action :require_date_range, only: :show

    def index
      @sites = ViewsPerDay.after(30.days.ago).order_by_totals.group_by_site
      redirect_to(site_path(@sites.first.host)) if @sites.size == 1
    end

    def show
      @histogram = Histogram.new(current_views_per_days.order_by_date.group_by_date, from_date, to_date)
      @previous_histogram = Histogram.new(previous_views_per_days.order_by_date.group_by_date, previous_from_date, previous_to_date)
      @referrers = current_views_per_days.top.group_by_referrer_site
      @pages = current_views_per_days.top.group_by_page
      @browsers = BrowsersPerDay.filter_by(params).group_by_name.top
    end
  end
end

app/helpers/active_analytics/application_helper.rb
module ActiveAnalytics
  module ApplicationHelper
    def format_view_count(number)
      number_with_delimiter(number.to_i)
    end
  end
end

app/helpers/active_analytics/browsers_helper.rb
module ActiveAnalytics
  module BrowsersHelper
    def browser_icon(browser_name)
      path = "browsers/#{browser_name.to_s.parameterize(separator: "_")}.svg"
      if AssetsController.endpoints.include?(path)
        image_tag(asset_url(path, host: request.host), alt: browser_name, class: "referer-favicon", width: 16, height: 16)
      else
        image_tag(asset_url("browsers/default.svg", host: request.host), alt: browser_name, class: "referer-favicon", width: 16, height: 16)
      end
    end
  end
end

app/helpers/active_analytics/page_views_helper.rb
module ActiveAnalytics
  module PageViewsHelper
  end
end

app/helpers/active_analytics/pages_helper.rb
module ActiveAnalytics
  module PagesHelper
    def page_to_params(name)
      name == "/" ? "index" : name[1..-1]
    end

    def page_from_params
      if params[:page] == "index"
        "/"
      elsif params[:page].present?
        "/#{params[:page]}"
      end
    end
  end
end

app/helpers/active_analytics/referrers_helper.rb
module ActiveAnalytics
  module ReferrersHelper
  end
end

app/helpers/active_analytics/sites_helper.rb
module ActiveAnalytics
  module SitesHelper
    def site_icon(host)
      image_tag("https://icons.duckduckgo.com/ip3/#{host}.ico", referrerpolicy: "no-referrer", class: "referer-favicon")
    end
  end
end

app/views/layouts/active_analytics/_footer.html.erb
<footer>
  <p>
    Made in <a href="https://www.basesecrete.com" target="_blank" rel="noopener">Base Secrète</a> | <%= link_to "Source code", "https://github.com/BaseSecrete/active_analytics", target: "_blank", rel: "noopener" %> | <%= link_to "Twitter", "https://twitter.com/base_secrete", target: "_blank", rel: "noopener" %>
  </p>
  
  <div class="card">
    <ul class="grid-auto">
      <li>
        <a href="https://github.com/BaseSecrete/rorvswild" target="_blank" rel="noopener">RoRvsWild</a>
        <p>Ruby on Rails application performances and exceptions monitoring.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/active_hashcash" target="_blank" rel="noopener">Active Hashcash</a>
        <p>Protect Rails applications against bots and brute force attacks without annoying humans.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/redis_dashboard" target="_blank" rel="noopener">Redis Dashboard</a>
        <p>Sinatra app to monitor Redis servers.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/type_scopes" target="_blank" rel="noopener">Type Scopes</a>
        <p>Automatic scopes for ActiveRecord models.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/teamodoro" target="_blank" rel="noopener">Teamodoro</a>
        <p>Synchronize pomodoros with your coworkers.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/ariato" target="_blank" rel="noopener">Ariato</a>
        <p>Web UI framework to improve accessibility.</p>
      </li>
    </ul>
  </div>
</footer>

<div role="dialog" hidden="true" id="custom-date-range" aria-labelledby="custom-range-title" aria-modal="true">
  <header id="custom-range-title">Custom range</header>
  <%= form_tag url_for(params.except(:from, :to).to_unsafe_hash), method: "get", id: "dateRangeForm" do %>
    <div role="group" class="is-block">
      <label>From <%= date_field_tag :from, params[:from] %></label>
      <label>To <%= date_field_tag :to, params[:to] %></label>
    </div>
  <% end %>
  <footer>
    <%= submit_tag "Change date range", form: "dateRangeForm" %>
    <button type="reset" onclick="Ariato.Dialog.close(this)">Close</button>
  </footer>
</div>

app/views/layouts/active_analytics/_header.html.erb
<header data-ariato="ActiveAnalytics.Header">
  <nav aria-label="site">
    <%= link_to active_analytics_path, class: 'logo' do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11 11">
        <path class="a" d="M.5,5.5s0,2,1,2,1-2,1-2,0-2,1-2,1,2,1,2,0,2,1,2,1-2,1-2,0-2,1-2,1,2,1,2,0,2,1,2,1-2,1-2"/>
        <circle class="a" cx="5.5" cy="5.5" r="5"/>
        <line class="a" x1="0.5" y1="5.5" x2="10.5" y2="5.5"/>
      </svg>
    <% end %>

    <% if params[:site] %>
      <%= link_to params[:site], site_path(params[:site], from: params[:from], to: params[:to]) %>
      
      <% if controller_name == "pages" %>
        &nbsp;/&nbsp;<%= link_to "pages", pages_path(params[:site], from: params[:from], to: params[:to]) %>
      <% end %>

      <% if controller_name == "referrers" %>
        &nbsp;/&nbsp;<%= link_to "referrers", referrers_path(params[:site], from: params[:from], to: params[:to]) %>
      <% end %>

      <div class="menubutton">
        <button type="button" id="date-range" aria-haspopup="true" aria-controls="date-range-menu">
          <%= l params[:from].to_date, format: :long %>
          <% if params[:to].to_date !=  params[:from].to_date %> → <%= l params[:to].to_date, format: :long %><% end%>
        </button>
        <ul id="date-range-menu" role="menu" aria-labelledby="date-range">
          <li role="none">
            <%= link_to "Today", url_for(params.merge(from: Date.today, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Yesterday", url_for(params.merge(from: Date.yesterday, to: Date.yesterday).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Last 7 days", url_for(params.merge(from: 7.days.ago.to_date, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Last 30 days", url_for(params.merge(from: 30.days.ago.to_date, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <button type="button" onclick="Ariato.Dialog.open('custom-date-range')"  tabindex="-1" class="is-link">
              Custom range
            </button>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/active_analytics/application.html.erb
<!DOCTYPE html>
<html class="active-analytics">
  <head>
    <title>Active analytics</title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= tag.link rel: "stylesheet", href: asset_path(:ariato, format: :css) %>
    <%= tag.link rel: "stylesheet", href: asset_path(:application, format: :css) %>
    <%= tag.script "", src: asset_path(:ariato, format: :js) %>
    <%= tag.script "", src: asset_path(:application, format: :js) %>
  </head>

  <body>
    <%= render "/layouts/active_analytics/header" %>
    <main aria-label="Content">
      <%= yield %>
    </main>
    <%= render "/layouts/active_analytics/footer" %>
  </body>
</html>